# Generated by Django 2.2.7 on 2020-03-05 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=1000)),
                ('username', models.TextField(max_length=1000)),
                ('year', models.TextField(max_length=1000)),
                ('city', models.TextField(max_length=1000)),
                ('price', models.TextField(max_length=1000)),
                ('description', models.TextField(max_length=1000)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suv.Category')),
            ],
        ),
    ]
