# Generated by Django 3.0.4 on 2020-03-06 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='username',
        ),
    ]
