# Generated by Django 2.2.7 on 2020-03-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suv', '0002_remove_transaction_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.TextField(default=0, max_length=1000),
        ),
    ]
