# Generated by Django 2.2.7 on 2020-03-06 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suv', '0003_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_image',
            field=models.ImageField(blank=True, null=True, upload_to="{% static 'img' %}"),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=1000)),
                ('time_range', models.TextField(max_length=1000)),
                ('date', models.TextField(max_length=1000)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suv.Car')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=1000)),
                ('message', models.TextField(max_length=1000)),
                ('created_date', models.TextField(max_length=1000)),
                ('rating', models.TextField(max_length=1000)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suv.Car')),
            ],
        ),
    ]
