# Generated by Django 3.0.4 on 2020-05-15 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suv', '0006_favoritecar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='category',
        ),
    ]
