# Generated by Django 3.0.4 on 2020-05-15 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suv', '0009_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='car_image',
        ),
    ]
